///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsScan = 'assets/scan.jpg';
  static const String drawerIconTablerHomeFilled =
      'assets/DrawerIcon/tabler_home-filled.svg';
  static const String fontsMedelRegular = 'assets/fonts/MedelRegular.ttf';
  static const String iconsAlert = 'assets/icons/alert.svg';
  static const String iconsApple = 'assets/icons/Apple.jpg';
  static const String iconsBankIcon = 'assets/icons/bank_icon.svg';
  static const String iconsCall = 'assets/icons/call.svg';
  static const String iconsCancel = 'assets/icons/cancel.svg';
  static const String iconsCar1 = 'assets/icons/car1.svg';
  static const String iconsEdit = 'assets/icons/edit.svg';
  static const String iconsFacebook = 'assets/icons/Facebook.png';
  static const String iconsGmail = 'assets/icons/Gmail.png';
  static const String iconsHistory = 'assets/icons/history .svg';
  static const String iconsHome = 'assets/icons/home.svg';
  static const String iconsIraq = 'assets/icons/iraq.png';
  static const String iconsListIcon = 'assets/icons/list_icon.svg';
  static const String iconsLogOut = 'assets/icons/log_out.svg';
  static const String iconsMapBlue = 'assets/icons/map_blue.svg';
  static const String iconsMapRed = 'assets/icons/map_red.svg';
  static const String iconsMessage = 'assets/icons/message.svg';
  static const String iconsMissionsIcon = 'assets/icons/missions_icon.svg';
  static const String iconsNotification = 'assets/icons/notification.svg';
  static const String iconsPhone = 'assets/icons/phone.svg';
  static const String iconsSearch = 'assets/icons/search.svg';
  static const String iconsSettingsIcon = 'assets/icons/settings_icon.svg';
  static const String iconsWalletIcon = 'assets/icons/wallet_icon.svg';
  static const String imagesBackArrow = 'assets/images/back_arrow.svg';
  static const String imagesCar = 'assets/images/car.png';
  static const String imagesCardImage = 'assets/images/Card_image.png';
  static const String imagesCheck = 'assets/images/check.svg';
  static const String imagesDotes = 'assets/images/dotes.svg';
  static const String imagesDrawer = 'assets/images/drawer.svg';
  static const String imagesDriverImage = 'assets/images/driver_image.jpg';
  static const String imagesDropMenu = 'assets/images/drop_menu.svg';
  static const String imagesFrom = 'assets/images/from.svg';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesMap = 'assets/images/map.png';
  static const String imagesPath4671 = 'assets/images/Path4671.png';
  static const String imagesPayment = 'assets/images/Payment.png';
  static const String imagesProfileImage = 'assets/images/profile_image.png';
  static const String imagesRectangle1271 = 'assets/images/Rectangle1271.png';
  static const String imagesSplashScreen = 'assets/images/SplashScreen.png';
  static const String imagesTo = 'assets/images/to.svg';
  static const String cash = 'assets/images/paymentimg.png';
}
